<script setup lang="ts">
import type { PxUserWidgetEvent } from '~/composables/usePxUserWidget'

/**
 * <px-user-forgot-password> — requests a password reset mail.
 *
 * Generated by `createWidgetElement('password-forgot', …)`, so it takes the base
 * attributes only and uses the default `success` event. It inherits
 * `showSuccessMessage = true`, meaning it renders its own confirmation into the
 * success span; the host page usually needs to do nothing on success.
 */
const props = withDefaults(
    defineProps<{
        containerId?: string
        minHeight?: string
    }>(),
    { containerId: 'px-user-forgot-password', minHeight: '260px' },
)

const emit = defineEmits<{
    success: [event: PxUserWidgetEvent]
    error: [event: PxUserWidgetEvent]
    reset: [event: PxUserWidgetEvent]
    mounted: [event: PxUserWidgetEvent]
}>()

const el = ref<HTMLElement | null>(null)

const attrs = usePxUserWidgetAttrs(() => props.containerId)
const widgetKey = usePxUserWidgetKey(attrs)

// The generated emit overloads can't take a name chosen at runtime, so widen
// it once here rather than casting at every call.
const forwardEvent = emit as unknown as (name: string, event: PxUserWidgetEvent) => void

usePxUserWidgetEvents(el, ['success', 'error', 'reset', 'mounted'], forwardEvent)

defineExpose({ el, attrs })
</script>

<template>
    <PxWidgetHost :min-height="minHeight">
        <px-user-forgot-password ref="el" :key="widgetKey" v-bind="attrs" />
    </PxWidgetHost>
</template>
